export const CHINESE_COMMUNICATION_LEXICON = [
  { zh: '我', synonyms: ['自己', '本人'], category: 'daily' },
  { zh: '你', synonyms: ['您'], category: 'daily' },
  { zh: '他', synonyms: [], category: 'daily' },
  { zh: '她', synonyms: [], category: 'daily' },
  { zh: '好', synonyms: ['可以', '行', '嗯', '好的', '对'], category: 'daily' },
  { zh: '不', synonyms: ['没', '不是', '否'], category: 'daily' },
  { zh: '有', synonyms: ['是', '对', '有的'], category: 'daily' },
  { zh: '谢谢', synonyms: ['感谢', '多谢'], category: 'emotions' },
  {
    zh: '想',
    synonyms: ['要', '想要', '希望', '需要', '需'],
    category: 'actions'
  },
  { zh: '去', synonyms: ['走', '出去'], category: 'actions' },
  { zh: '来', synonyms: ['过来'], category: 'actions' },
  { zh: '吃', synonyms: ['进食', '用餐', '吃饭'], category: 'actions' },
  { zh: '喝', synonyms: ['饮'], category: 'actions' },
  { zh: '看', synonyms: ['看看', '瞧'], category: 'actions' },
  { zh: '听', synonyms: ['听听'], category: 'actions' },
  { zh: '说', synonyms: ['讲', '告诉'], category: 'actions' },
  { zh: '玩', synonyms: ['游戏'], category: 'actions' },
  { zh: '休息', synonyms: ['歇', '歇歇'], category: 'actions' },
  { zh: '睡觉', synonyms: ['睡', '躺', '困'], category: 'actions' },
  { zh: '起床', synonyms: ['起来'], category: 'actions' },
  { zh: '坐', synonyms: ['坐下'], category: 'actions' },
  { zh: '站', synonyms: ['站起来'], category: 'actions' },
  { zh: '走', synonyms: ['走路', '散步'], category: 'actions' },
  { zh: '跑', synonyms: ['跑步'], category: 'actions' },
  { zh: '帮忙', synonyms: ['帮', '帮助', '请帮', '求助'], category: 'actions' },
  { zh: '叫', synonyms: ['喊', '叫人', '找'], category: 'actions' },
  { zh: '买', synonyms: ['购买', '购物'], category: 'actions' },
  { zh: '洗手', synonyms: ['洗'], category: 'actions' },
  { zh: '刷牙', synonyms: ['刷'], category: 'actions' },
  { zh: '不要', synonyms: ['不想', '不需要', '不用'], category: 'actions' },
  { zh: '回家', synonyms: ['回去'], category: 'actions' },
  { zh: '开心', synonyms: ['高兴', '快乐', '愉快'], category: 'emotions' },
  { zh: '伤心', synonyms: ['难过', '不开心', '悲伤'], category: 'emotions' },
  { zh: '害怕', synonyms: ['怕', '恐惧', '吓'], category: 'emotions' },
  { zh: '喜欢', synonyms: ['爱', '喜爱'], category: 'emotions' },
  {
    zh: '痛',
    synonyms: [
      '疼',
      '疼痛',
      '难受',
      '头疼',
      '头痛',
      '肚子疼',
      '肚子痛',
      '腰疼',
      '腰痛',
      '牙疼',
      '牙痛',
      '胸疼',
      '胸痛',
      '背疼',
      '背痛',
      '腿疼',
      '腿痛'
    ],
    category: 'medical'
  },
  { zh: '饿', synonyms: ['肚子饿', '饥饿'], category: 'emotions' },
  { zh: '渴', synonyms: ['口渴'], category: 'emotions' },
  { zh: '冷', synonyms: ['寒冷', '好冷'], category: 'emotions' },
  { zh: '热', synonyms: ['好热', '很热'], category: 'emotions' },
  {
    zh: '生病',
    synonyms: ['病了', '不舒服', '感冒', '着凉'],
    category: 'medical'
  },
  {
    zh: '累',
    synonyms: ['疲惫', '疲劳', '很累', '好累', '没力气'],
    category: 'medical'
  },
  { zh: '发烧', synonyms: ['发热', '高烧', '烧'], category: 'medical' },
  { zh: '咳嗽', synonyms: ['咳', '一直咳', '干咳'], category: 'medical' },
  { zh: '头晕', synonyms: ['晕', '眩晕', '头昏'], category: 'medical' },
  { zh: '恶心', synonyms: ['想吐', '呕吐', '反胃', '吐'], category: 'medical' },
  {
    zh: '呼吸困难',
    synonyms: ['喘不过气', '气促', '透不过气'],
    category: 'medical'
  },
  { zh: '出血', synonyms: ['流血', '伤口流血'], category: 'medical' },
  { zh: '换衣服', synonyms: ['换衣', '穿衣服'], category: 'daily' },
  { zh: '运动', synonyms: ['锻炼', '健身', '做运动'], category: 'actions' },
  { zh: '看电视', synonyms: ['电视', '开电视'], category: 'daily' },
  { zh: '理发', synonyms: ['剪头发', '剪发'], category: 'daily' },
  { zh: '看书', synonyms: ['读书', '阅读'], category: 'daily' },
  { zh: '妈妈', synonyms: ['妈', '母亲'], category: 'people' },
  { zh: '爸爸', synonyms: ['爸', '父亲'], category: 'people' },
  { zh: '哥哥', synonyms: ['兄弟'], category: 'people' },
  { zh: '姐姐', synonyms: ['大姐', '姐'], category: 'people' },
  { zh: '妹妹', synonyms: ['小妹', '妹'], category: 'people' },
  { zh: '医生', synonyms: ['大夫', '看病'], category: 'people' },
  { zh: '老师', synonyms: [], category: 'people' },
  { zh: '朋友', synonyms: [], category: 'people' },
  { zh: '家', synonyms: ['房子'], category: 'places' },
  { zh: '医院', synonyms: ['看病'], category: 'places' },
  { zh: '学校', synonyms: [], category: 'places' },
  { zh: '公园', synonyms: ['花园'], category: 'places' },
  { zh: '超市', synonyms: ['商店', '商场', '购物'], category: 'places' },
  { zh: '厕所', synonyms: ['洗手间', '卫生间', '上厕所'], category: 'daily' },
  { zh: '水', synonyms: ['饮水', '喝水', '杯水'], category: 'food' },
  { zh: '饭', synonyms: ['米饭', '吃饭', '餐'], category: 'food' },
  { zh: '牛奶', synonyms: ['奶'], category: 'food' },
  { zh: '茶', synonyms: ['喝茶'], category: 'food' },
  { zh: '咖啡', synonyms: [], category: 'food' },
  { zh: '面包', synonyms: [], category: 'food' },
  { zh: '苹果', synonyms: [], category: 'food' },
  { zh: '香蕉', synonyms: [], category: 'food' },
  { zh: '鸡蛋', synonyms: ['蛋'], category: 'food' },
  { zh: '鱼', synonyms: [], category: 'food' },
  { zh: '饼干', synonyms: [], category: 'food' },
  { zh: '糖', synonyms: ['糖果'], category: 'food' },
  { zh: '冰淇淋', synonyms: ['雪糕'], category: 'food' },
  { zh: '药', synonyms: ['吃药', '服药', '药物'], category: 'objects' },
  { zh: '手机', synonyms: ['电话', '打电话'], category: 'objects' },
  { zh: '钱', synonyms: ['付钱'], category: 'objects' },
  { zh: '车', synonyms: ['汽车', '开车'], category: 'objects' },
  { zh: '花', synonyms: [], category: 'objects' },
  { zh: '今天', synonyms: [], category: 'time' },
  { zh: '明天', synonyms: [], category: 'time' },
  { zh: '昨天', synonyms: [], category: 'time' },
  { zh: '现在', synonyms: [], category: 'time' },
  { zh: '早上', synonyms: ['上午'], category: 'time' },
  { zh: '下午', synonyms: [], category: 'time' },
  { zh: '今晚', synonyms: ['晚上'], category: 'time' },
  { zh: '早饭', synonyms: ['早餐'], category: 'food' },
  { zh: '午饭', synonyms: ['午餐', '中饭'], category: 'food' },
  { zh: '晚饭', synonyms: ['晚餐'], category: 'food' },
  { zh: '和', synonyms: ['跟', '与'], category: 'daily' }
];

const zhIndex = new Map();
const synonymIndex = new Map();

CHINESE_COMMUNICATION_LEXICON.forEach(entry => {
  zhIndex.set(entry.zh, entry);
  entry.synonyms.forEach(synonym => {
    synonymIndex.set(synonym, entry);
  });
});

export function findChineseCommunicationEntry(word) {
  return zhIndex.get(word) || synonymIndex.get(word);
}
